### ISSUE TITLE
Will Pause, But Won't Minimise 

### ISSUE THREAD

**Issue by smhmd** [detuur/mpv-scripts#1]
OS: ubuntu 18.04
MPV: mpv git-2019-04-25-71ad1e2

"b" will pause but won't minimise the player; fullscreen and normalscreen.
if you need any more information.

**Comment by moppman** [comment]
You're probably missing `xdotool`, which is called by the script to minimize mpv. (see comment in `boss-key.lua`)
`sudo apt install xdotool` should do the job :)
edit: @detuur 
maybe add `xdotool` to the readme as requirement?

**Comment by detuur** [comment]
Done. I had completely forgotten about this issue so thanks for resolving it.
