### ISSUE TITLE
Slow startup when using boss-key.lua

### ISSUE THREAD

**Issue by rohitghali** [detuur/mpv-scripts#4]
There's a noticeable startup delay when using boss-key.lua. If I remove it, player starts instantly. Please do fix it. Other than than that, fantastic.

**Comment by detuur** [comment]
Took a while for me to get around to this, but if you still use it or would be willing to test again, could you quantify how many seconds?

**Comment by rohitghali** [comment]
How do I measure the exact delay? There's a 1.5 to 2 second delay. But how do I measure exactly? Any way of capturing a log?

**Comment by detuur** [comment]
No that's accurate enough. It's just to get an idea of the scale of the issue. If it's mere milliseconds or tens of seconds.

Could you give me the following details?

- Operating system
- mpv version
- Other plugins

As a matter of fact, a zip of your mpv directory could be very helpful.

**Comment by rohitghali** [comment]
OS-Windows

mpv details-:
mpv 0.34.0-198-gbc9805c71a Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 13 09:10:01 +08 2022
FFmpeg library versions:
   libavutil       57.21.100
   libavcodec      59.20.100
   libavformat     59.17.101
   libswscale      6.5.100
   libavfilter     8.27.100
   libswresample   4.4.100
FFmpeg version: git-2022-02-12-fad5c6d7

Here's my config folder zip:
[mpv_folder.zip](https://github.com/detuur/mpv-scripts/files/8133865/mpv_folder.zip)
I tried clearing the watch later list. No difference. There is just a little lag. Like 1 second probably. But it is definitely noticeable.

**Comment by detuur** [comment]
I have managed to reproduce the delay. It's indeed relatively minor, but I'm going to look into solutions either way.

**Comment by detuur** [comment]
Resolved in fb8a6258c692761ff94ffcba0edafaa676702bf8

Give it a spin.

**Comment by rohitghali** [comment]
I think it's better. At this point, I don't even know. I'll use it for a while. Let's see.
