### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [detuur/mpv-scripts#8]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by detuur** [comment]
I don't use mplug, so I can't test this. You are welcome to write a manifest, test it, and submit a pull request.

**Comment by detuur** [comment]
I'm closing this for now, as there doesn't seem to be any demand for this integration. You're still welcome to write, test, and submit a PR for it.
