### ISSUE TITLE
mpv not closing, have to end task everytime.

### ISSUE THREAD

**Issue by WhoMI7** [detuur/mpv-scripts#9]
Weird bug maybe. But only persists when `boss-key.lua` is in scripts directory.
logs: 
[6y0dbg.log](https://github.com/detuur/mpv-scripts/files/10549234/6y0dbg.log)

**Comment by detuur** [comment]
Odd. Could you make a zip of your mpv directory?

**Comment by WhoMI7** [comment]
Couln't upload to github directly https://drive.google.com/file/d/1G2iJFoehIP6ENPsGq8i2NfZu1cwcv9m9/view?usp=share_link
https://www.virustotal.com/gui/file/664f37648068c46cb86c2fea8c97c1e11d5bbf0b4526d0d731768aceecc51de8?nocache=1

**Comment by WhoMI7** [comment]
w8 if you meant config directory then it is [Dyphire's build `mpv_config-2023.01.22.7z`](https://github.com/dyphire/mpv-config/releases/tag/mpv_config-2023.01.23)
Though I think it is becasue of [mpv-segment-linking](https://github.com/CogentRedTester/mpv-segment-linking) script.
